### ISSUE TITLE
Missing date in messages: Message struct Date field is zero in basic group chats but not in Channels or supergroups.

### ISSUE THREAD

**Issue by spacemolly** [gotd/td#284] opened 2021-04-09 10:55 UTC
### What version of gotd are you using?

<pre>
$ go list -m github.com/gotd/td
github.com/gotd/td v0.33.1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?
I receive messages thorough OnNewMessage but the .Date field is zero (not set)

### What did you expect to see?

When I receive message in OnNewChannelMessage the .Date field is a unix time stamp. Expect it to be same for non-group chat messages.

### What did you see instead?

.Date field is zero (not set)

### What Go version and environment are you using?

<pre>
$ go version
go version go1.16 darwin/amd64
</pre>

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Library/Caches/go-build"
GOENV="/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/j1/hgqrbz2n1xsgz6_2c0slq9nh0000gn/T/go-build3091972184=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

**Comment by ernado** [comment] 2021-04-09 11:33
Thank you for report! We've already found the cause for this bug (handling of short updates), fix is in progress.

**Comment by spacemolly** [comment] 2021-04-09 11:36
That's really great. Thanks for your work, just started using it but this is a great project!

**Closed** 2021-04-09 11:42 UTC
Labels: area: client, bug

**Comment by ernado** [comment] 2021-04-09 11:43
Please try `v0.33.2`

**Comment by spacemolly** [comment] 2021-04-09 12:38
Works!
